# CONTRIBUTE

## **How to Contribute New E-Device Research: Two Ways** {-}

<!-- # specifying font style for bold because H3 does not render bold "**" option-->
::: {#Tab1  style="font-size:18px; font-family: Segoe UI;"}
**Best Way: Submit changes to the e-device package using Github:** 
:::

  a. Create a fork off of the primary package: https://github.com/InteragencyEcologicalProgram/e-device

  b. Clone this fork to your own local repository

  c. Render the book:

      -  Click on the 'Build' pane in the RStudio IDE and Click on 'Build Book' tool

      -  Or, build the book from the R console:

```{r, eval=FALSE}
bookdown::render_book()
```

  d. Compose changes or updates to the book contents
  
  e. Render the book after you make changes

  f. Submit a pull request with your revisions

<!-- # specifying font style for bold because H3 does not render bold "**" option-->
::: {#Tab1  style="font-size:18px; font-family: Segoe UI;"}
**Back-up Way: Email proposed changes/edits to the document manager:** 
:::

  a. Print to pdf each page of the document that needs to be changed using the web browser print options and use a pdf editor to insert comments or changes, 
  Or, just note the bookdown page and the changes needed in a text document.

  b. E-mail these edits to: karrin.alstad@wildlife.ca.gov

